version: "2.3"

services:  
  uoc-cloud:
    build:
      context: .
    volumes: 
      - ./cfg/:/cfg/
    environment:
      - URL_UOC=django
      - PORT_UOC=8000
    command: sh -c "python3 src/main.py"
    restart: unless-stopped
    
volumes:
    django_postgres: